var express             =   require("express");
var ExpressSession      =   require('express-session');
var googleAPI           =   require('googleapis');
// var googleAuth          =   require('google-auth-library');
var bodyParser          =   require("body-parser");
var router              =   express.Router();
var app                 =   express();
var path                =   require("path");
var http				=	require('http');
var authenticate		= 	require('./authentication.js');
var url 				= 	require('url');  
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({"extended" : true}));

app.set('json spaces', 3);
app.use(ExpressSession({
    secret: 'calendar-secret-19890913007',
    resave: true,
    saveUninitialized: true
}));

// app.set('views', path.join(__dirname, 'views'));
//app.set('view engine', 'html');
app.use(express.static(path.join(__dirname, 'public')));
app.engine('html', require('ejs').renderFile);
app.use('/',router);  

router.get("/",function(req,res){
   res.sendFile(path.join(__dirname+'/views/index.html'))
});


app.get("/checkLogin",function(req,res){
	console.log("incoming");
	// authenticate.authenticateUserLogin(req,function(status,message,cookiePackage){
	// 	console.log(status+" "+message+" "+cookiePackage);


	// 	//example access token generated by google OAuth
		// var tokens= {
  //       "access_token": "ya29.GlvjBHvDVS5NzQok4DAaI4U2tGa78q6O-4cLuM7hapQ7IlU7iysB4Na8DGhD87VNVtUYEgWYNjuyICKBYn7BRfAeF1V-JtzLrlKrOSTgpxf2PEt2cjYdKJhspU9y",
  //       "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmOTk1MjVjYzNhMzNlM2MyYjVkY2Y5YTIxZjRkODJkMzcxYmU3NjcifQ.eyJhenAiOiIzNTgwNzA3MDE2NjktNWRiamhiNjM2a2NhaTBkMDV0ODExcG1oaWVlNHJxczIuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIzNTgwNzA3MDE2NjktNWRiamhiNjM2a2NhaTBkMDV0ODExcG1oaWVlNHJxczIuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDcyNDY5OTI2ODEwNzU5MDc5ODciLCJlbWFpbCI6InNoYXJhdC5uLmhlZ2RlQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiV1VXb0pJOGVGM3lyVFc4VGo3MHFsZyIsImlzcyI6ImFjY291bnRzLmdvb2dsZS5jb20iLCJpYXQiOjE1MDc4NjkwNjUsImV4cCI6MTUwNzg3MjY2NX0.kOSJBh-igNjjF8WSy2voLnuJuy22k3rI6SLcSgsZmynaBOp9H8SU7jh1KNB6DGHXt1Rp0RkBftsaBNR2JoVMJs7l7Kvrl0Yg4WBwBPoiTWmLUDIQ1-HkXaBPfD5RopgINmQvcojA_SxTmiek90nnxTeQiGVuLNBk8sHlEfy5sOt9_-z3tvnFDgGmC5wneXz-nF6PPKrx64fo75iAwAyI8XJCgG2-7WFIdTpRgnRLh0EkHGZBdmWHlJaC4s1hKlW-Hj10cUC0nIchvZ73TOQZf8XaKfokHhsZQDVAGhroJk1WtZVl4Kb5LrCH0SwcVT2nwY5gbKRjSsqh4IWnKHNImQ",
  //       "refresh_token": "1/8JtqVUs0iD--DM_Tqf2OiXrchgcqMXH-kRChvzzMmtY",
  //       "token_type": "Bearer",
  //       "expiry_date": 1507872665146
  //   };

  //   var result={
  //     message:"Login Successful!",
  //     userType:"doctor"
  //   }
  //   res.send(result);
  //   	//generate the redirect URL
		// var redirectURL=url.format({
  //      		pathname:"http://localhost:5000/landingpage.html",
		//     query: {
		//           "email": "sharat.n.hegde@gmail.com",
  //             "user_type":"doctor"
		//           "token": tokens
		//         }
  //    	});

		// console.log(redirectURL);
	// 	res.location(redirectURL);

	// 	res.writeHead(302, {
 //  			'Location': redirectURL
	// 		});
	// 	res.end();

	// })
})


app.get("/landingpage.html/",function(req,res){
   res.sendFile(path.join(__dirname+'/views/landingpage.html'))
});

router.get("/Dashboard/",function(req,res){
   res.sendFile(path.join(__dirname+'/views/DashboardTrial.html'))
});

router.get("/register.html/",function(req,res){
   res.sendFile(path.join(__dirname+'/views/register.html'))
});

router.get("/error.html/",function(req,res){
   res.sendFile(path.join(__dirname+'/views/error.html'))
});

console.log(process.env.PORT);
var port = process.env.PORT || 5000;
app.listen(port);
console.log("Listening to PORT "+ port);

var http = require ('http');
