var states = {
	REGULAR_SESSION : "REGULAR_SESSION",
	SYMPTOMS_SESSION: "SYMPTOMS_SESSION",
	SYMPTOMS_SESSION_IN: "SYMPTOMS_SESSION_IN",
	APPOINTMENT_SESSION: "APPOINTMENT_SESSION"
};

module.exports = {states};